### ISSUE TITLE
Phoenix LiveView 1.2.0-rc.3 HEEx compiler rejects case branches in AshAdmin components

### ISSUE THREAD

**Issue by jeffhuen** [ash-project/ash_admin#403]
## Summary

`ash_admin` 1.1.0 fails to compile with `phoenix_live_view` 1.2.0-rc.3 because the LiveView 1.2 HEEx compiler rejects the older case-branch template style used in several AshAdmin components.

## Environment

- `ash_admin`: 1.1.0
- `phoenix_live_view`: 1.2.0-rc.3
- `phoenix`: 1.8.7
- `elixir`: 1.20.0-rc.6

## Repro

In a Phoenix app using AshAdmin, update LiveView to the 1.2 RC line and compile:

```elixir
{:ash_admin, "~> 1.1"},
{:phoenix_live_view, "~> 1.2.0-rc.3"}
```

```sh
mix deps.update phoenix_live_view ash_admin
mix compile
```

## Observed

Compilation fails inside AshAdmin:

```text
== Compilation error in file lib/ash_admin/components/page_header.ex ==
** (SyntaxError) invalid syntax found on lib/ash_admin/components/page_header.ex:160:12:
     error: syntax error before: '->'
     │
 160 │   [single] ->  __EEX__(0);
     │            ^
     └─ lib/ash_admin/components/page_header.ex:160:12
    (phoenix_live_view 1.2.0-rc.3) lib/phoenix_live_view/tag_engine/compiler.ex:213: Phoenix.LiveView.TagEngine.Compiler.handle_node/3
```

The first failing site is `AshAdmin.Components.PageHeader.create_action_button/1`. A grep of current `main` shows the same older HEEx case-branch style in a few places that are likely affected:

- `lib/ash_admin/components/page_header.ex` around the read/create action switchers
- `lib/ash_admin/components/resource/data_table.ex` around update/destroy action dropdown rendering
- `lib/ash_admin/components/resource/generic_action.ex` around result rendering

Example pattern:

```heex
<%= case @create_actions do %>
  <% [] -> %>
  <% [single] -> %>
    ...
  <% actions -> %>
    ...
<% end %>
```

## Expected

`ash_admin` should compile with LiveView 1.2.0-rc.3.

## Notes

`ash_authentication_phoenix` had a similar compatibility issue on its 2.x line, but `3.0.0-rc.6` compiles and its changelog mentions LiveView 1.2 compatibility. AshAdmin 1.1.0 and current `main` still appear to contain this syntax.

A compatible fix is to move the branch dispatch into normal Elixir and render each branch as a small `~H` block, or otherwise rewrite these templates so the `->` clauses are no longer parsed as HEEx nodes.
